### ISSUE TITLE
Add a "Certificate" field

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-pro-for-wsl#802]
In this UI, if the only information missing to have the equivalent of the configuration file is the certificate, then there should be a file chooser field to select the certificate. The operation is much simpler for the user than typing the configuration in a text file, then selecting the text file from this UI.

![Capture d'écran 2024-06-14 113247](https://github.com/canonical/ubuntu-pro-for-wsl/assets/1928546/d0016448-8535-4ebf-8922-e3c1164ef7da)

And remove "Account Name" and "Registration Key" which are only valid on Landscape SaaS

**Comment by CarlosNihelton** [comment]
> And remove "Account Name" and "Registration Key" which are only valid on Landscape SaaS

"Registration key" is valid in both self-hosted and SaaS offerings, thus we cannot remove it.

**Comment by CarlosNihelton** [comment]
This bug report is about the following page (as seen in the original Figma design):
![The original Figma design](https://github.com/user-attachments/assets/282ccd8a-b7e6-472a-932f-315d5e6993a8)

As we iterate over testing the product together with Landscape we noticed the frequent need to use the the `Custom Configuration` option (which requires writing a conf file, certainly not as easy as filling a three field form) just because our setup required informing the self-hosted Landscape SSL certiticate (aka public key). We believe that customers with self-hosted Landscape servers are likely to pass custom certificates to their internal clients, so offering an input field for that value could result in improved UX.

But that page seems already too busy with always visible input fields grouped into two subforms. Adding a 4th input field to the top subform without further design thinking seems not the best option. Additionally there are some interleaving logic around the four fields falling into two possible scenarios:

1. If the server is `landscape.canonical.com` (aka Landscape SaaS), then `Landscape server address`, `Landscape Account name` and `Registration key` must be interactive, while the `SSL public key` should be disabled.   `Registration key` is optional but `Landscape Account name` is required and must not be `standalone`.

2. otherwise `Landscape server address`, `Registration key`  and `SSL public key` must be interactive. `Landscape Account name` could be shown containing the `standalone` value but disabled so users cannot change it. Alternatively that field could be entirely removed, as the business logic would attribute the value `standalone` to it. `Registration key`  and `SSL public key` are optional in this scenario.

Below I present two alternatives ideas that describe well the interleaved logic. Can we use them as input for the Design team to come up with an actual design proposal?

1. Mutual exclusive fields being replaced with some animation hinting the change in the form

https://github.com/user-attachments/assets/36ccbf05-25c4-465c-95c9-4290f631d34a



2. Collapsible subforms with all fields visible when subform is expanded

https://github.com/user-attachments/assets/b80e40fd-863e-4776-a8c5-85e7613d69fd



The entire wizard design can be found at: https://www.figma.com/design/Ur0hDHKPvjwWeBbuH9xtqC/Ubuntu-Pro-for-Windows-%2F-WSL?node-id=552-2390&t=XhIUGAXE8WyaiNz9-0
The scenarios described above are also present in the form of comments in the original Figma design files, except that they didn't consider the ´SSL public key` option.

@anasereijo can we get your input on this matter? Should I fill [this form](https://warthogs.atlassian.net/jira/software/c/projects/WD/forms/form/direct/4/10013) or an equivalent?

**Comment by danielmutis** [comment]
@CarlosNihelton I am the designer on Landscape. 

Just one clarification: does a user that want to add a custom config file not need to add any details about the Landscape server address or the certificate? or is the config file an addition to the information required in the quick set up?

Regardless, the second option you provided is much clearer and a much better experience.

**Comment by CarlosNihelton** [comment]
Hi @danielmutis !

All those options must be present in the config file, plus a variety of other options that the Landscape client config offers. One filing the file is considered a power user.

The alternative of the "Quick Setup" is for those not willing to dig to much, but rather changing the more common options, relying that the application will assemble the equivalent configuration data.

**Comment by CarlosNihelton** [comment]
> Regardless, the second option you provided is much clearer and a much better experience.

Should I move forward with that option or request a design based on that through some standard form/procedure?

**Comment by jibel** [comment]
Another proposal would be to:
* Move the static title from the left pane to the top
* Display the 3 options as radio buttons on the left pane:
  * Landscape SaaS
  * Landscape hosted
  * Custom configuration
* Display the fields on the right pane depending the selected option

This avoids collapsible radio buttons and uses most of the space of the UI.

WDYT?

**Comment by danielmutis** [comment]
@jibel I like this option. Yesterday I suggested to @CarlosNihelton to split it into 3 radios so that we don't have the in-form validation making the field disabled, which is odd in my opinion. However, is the left side used to control the right side on other steps of this wizard? If not, it may be a bit of an odd interaction to add only in this step. I am not too concerned about the way in which content is being shown and hidden at the moment, since this is a common UX pattern ([progressive disclosure](https://www.nngroup.com/articles/progressive-disclosure/)).

**Comment by jibel** [comment]
It's actually the only page of the wizard where we really have a form. On the first page there is only one field to enter a token.

**Comment by CarlosNihelton** [comment]
https://github.com/user-attachments/assets/80ce235f-230f-4402-a9ce-1e0dfe5e3e5b



This proposal goes in line with jibel's suggestion. While it's significantly different from the original design mock ups and also deviate from the proposed Landscape config page for the ubuntu-desktop-provision, I honestly think this is the best composition to show only the relevant fields and better use the screen real estate.

There will always be a busier side, but I think this is better than offering buttons to navigate to three different pages.

WDYT?

**Comment by jibel** [comment]
Thanks for this proposal, it looks very good to me.

I'd remove the sentence "Select which option best describes your setup" , there is already an explanation below each option. Or I would change it to something like "Configure the connection to Landscape:" or "Configure the Landscape client:"

For the "Custom configuration", I'd use "Load a custom Landscape client configuration file"

@danielmutis What do you think of Carlos' last proposal?

**Comment by danielmutis** [comment]
@jibel @CarlosNihelton I think the last proposal looks good. I think, visually, maybe having the vertical line between the radiobuttons and the fields would help visualise the relationship between them, as right now it may look like the fields are unrelated to the radios. Otherwise, I agree that it's the best interaction so far.

**Comment by CarlosNihelton** [comment]
Great! I'm going to move the implementation forward with the suggested vertical divider. Thanks for the guidance @danielmutis !

**Comment by CarlosNihelton** [comment]
> For the "Custom configuration", I'd use "Load a custom Landscape client configuration file"

That would be a too big title for the radio (too different from the other options), but it's good for the subtitle. I'm replacing the title with "Advanced Configuration" since that's the use case the config file input is for.

![image](https://github.com/user-attachments/assets/9a28a616-e715-4171-8282-341824f84200)

vs

![image](https://github.com/user-attachments/assets/69a2db00-e4e4-4ba7-a739-8c2e15713817)

**Comment by CarlosNihelton** [comment]
Closed by #849 .
